### ISSUE TITLE
Unable to find plugin

### ISSUE THREAD

**Issue by williamhibberd** [fruitstudios/craft-postmen#1]
Just wondering if this is fully released as I cannot find it on the plugin store.

**Comment by samhibberd** [comment]
@williamhibberd no not as yet, was written for a single project although it is being used in production.

It's on packagist and will likely be maintained as long as it's required, feel free to grab a copy, use, contribute etc etc

`composer require fruitstudios\postmen`

Usual disclaimer, no docs and use at own risk 😄

**Comment by williamhibberd** [comment]
Thanks Sam, I will check it out. 

Not often you bump into another Hibberd in the UK wearing cycling kit on github.
